#docker-compose.yml
#This file is used to define and run multi-container Docker applications. 
#It allows you to configure your application's services, networks, 
#and volumes in a single file, making it easier to manage and deploy your application.
services: 
  influxdb:
    container_name: g8-influxdb-Nimbus-Server
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: Nimbus
      DOCKER_INFLUXDB_INIT_PASSWORD: NimbusWeather26
      DOCKER_INFLUXDB_INIT_ORG: Nimbus
      DOCKER_INFLUXDB_INIT_BUCKET: Nimbus 
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    restart: unless-stopped
  rabbitmq:
    container_name: g8-rabbitmq-Nimbus-Server
    image: rabbitmq:3.12-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: Nimbus
      RABBITMQ_DEFAULT_PASS: Nimbus
      RABBITMQ_ALLOW_REMOTE_LOGON_USER: "true"
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s
volumes:
  influxdb-data:
 